package com.example.ecommerceanalytics.controller;

import com.example.ecommerceanalytics.entity.FlashSaleAlert;
import com.example.ecommerceanalytics.service.AlertService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.RequiredArgsConstructor;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping("/alerts")
@RequiredArgsConstructor
@Tag(name = "Alerts", description = "APIs for flash sale alerts")
public class AlertController {

    private final AlertService alertService;

    @GetMapping
    @Operation(summary = "Get all alerts", description = "Returns all flash sale alerts generated by Spark")
    public List<FlashSaleAlert> getAllAlerts() {
        return alertService.getAllAlerts();
    }

    @GetMapping("/product/{productId}")
    @Operation(summary = "Get alerts by product ID", description = "Returns flash sale alerts for a specific product")
    public List<FlashSaleAlert> getAlertsByProductId(@PathVariable String productId) {
        return alertService.getAlertsByProductId(productId);
    }
}